version: '3.4'
services:
  tf1:
    image: gcr.io/tensorflow/tensorflow:latest-devel
    volumes:
      - ./data/trn:/tf_files/data
      - ./set1/bottlenecks:/tf_files/bottlenecks
      - ./set1/out:/tf_files/out
    working_dir: /tf_files
    command: tail -f /dev/null
